### ISSUE TITLE
Loss can be Nan in some cases

### ISSUE THREAD

**Issue by Cjkkkk** [ryanchankh/mcr2#1]
`compress_loss_empi` calculated in `MaximalCodingRateReduction` can be `Nan` in some cases because the argument passed to `logdet` is negative.

**Comment by Cjkkkk** [comment]
https://github.com/pytorch/pytorch/issues/22848
It seems there are bugs in pytorch logdet implementation.

**Comment by ryanchankh** [comment]
That's interesting. The pull request you linked is also very recent. Seems
like a lot of people are getting this problem also.
