### ISSUE TITLE
None defined `supervised` fuction in cluster.py

### ISSUE THREAD

**Issue by chengwuxinlin** [ryanchankh/mcr2#18]
The function clustering_accuracy in cluster.py includes an undefined function, it is located in line 607. 

`labels_true, labels_pred = supervised.check_clusterings(labels_true, labels_pred)`

could you please tell me what function is `supervised`? Thanks

**Comment by ryanchankh** [comment]
The function comes from an other version scikit-learn. You may update the new function call if you want to use a newer version of scikit-learn. 

https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/metrics/cluster/_supervised.py

Hope this helps!

**Comment by chengwuxinlin** [comment]
> The function comes from an other version scikit-learn. You may update the new function call if you want to use a newer version of scikit-learn.
> 
> https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/metrics/cluster/_supervised.py
> 
> Hope this helps!

Thanks for the help!
