### ISSUE TITLE
Why the "compute_compress_loss_empirical" is same as the "compute_compress_loss_theoretical" in loss.py?

### ISSUE THREAD

**Issue by wenhaozheng-nju** [ryanchankh/mcr2#2]
I found these two function in loss.py is the same except the order of computing  the "compress_loss".

**Comment by ryanchankh** [comment]
which two loss function?

**Comment by fingertap** [comment]
They modified the empirical version and now they use $k$ samples. However, the original version of "compute_compress_loss_empirical" is identical to the "compute_compress_loss_theoretical".

Somehow, the problem cannot be found in current version, or even in historical commits.

Given this issue, I am concerned about the correctness of the results reported in the paper, as the codes released contain crucial bugs in the loss function definition.

**Comment by yaodongyu** [comment]
@fingertap Could you describe your question/problem explicitly? What are the so-called "crucial bugs"? You could use the permalink for reference.

**Comment by fingertap** [comment]
![image](https://user-images.githubusercontent.com/7274689/101774250-ce408e80-3b28-11eb-8dfb-af88aaac7552.png)
![image](https://user-images.githubusercontent.com/7274689/101774262-d1d41580-3b28-11eb-82f7-e451e1e6f69a.png)

This is what I saw last time (26th, Nov), which indicates the two loss functions are the same. But today, somehow the loss functions are different, and I cannot see the commits.

Given the fact that the change is after this issue, I doubt whether your original implementation is correct, as the loss functions are **crucial** to a ML problem.

**Comment by fingertap** [comment]
What a coincidence. I am not the only one that noticed this identical loss issue, as you see, the issue is not opened by me.

**Comment by fingertap** [comment]
Originally, I thought it was just a bug, as this project seems very solid, as there are 200+ commits. However, at this point, given that the loss function implementations are changed without any direct replies to this issue, I doubt the correctness of this work.

**Comment by yaodongyu** [comment]
@fingertap These two losses should be the same.

**Comment by yaodongyu** [comment]
@fingertap If you have questions about the correctness, please read the paper and then you could compare the implementation with our paper.
